export const items =  [
    {
      id: 1,
      category: 'iphone',
      title: "Apple iPhone 14",
      imgSrc: 'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-14-finish-select-202209-6-1inch-blue?wid=5120&hei=2880&fmt=webp&qlt=70&.v=bjlYUjk1NXN2Uy9CTWFMaXBneUF0bEthL1VsNXgveGUwQ1JqNzA0ZHAra2lYQ0tYMHd1OS9ZREtnNzFSR1owOHF2TWlpSzUzejRCZGt2SjJUNGl1VEtsS0dZaHBma3VTb3UwU2F6dkc4TGUyZW92SlBoRGNVUmdGRkF6QU0rNmI=&traceId=1',
      amazonLink: 'https://www.apple.com/th/shop/buy-iphone/iphone-14',
      description: 'Apple iPhone 14 (128 GB)',
      price: '22900',
    },
    {
      id: 5,
      category: 'Mac',
      title: "MacBook Air รุ่น 13 M2",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://www.apple.com/th/macbook-air/',
      description: 'ขนาด 13.6 นิ้ว หรือ 15.3 นิ้ว2 256GB ถึง 2TB',
      price: '43900',
    },
    {
      id: 7,
      category: 'ipad',
      title: "iPad Pro รุ่น 11 นิ้ว",
      imgSrc: 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/ipadpro11-digitalmat-gallery-1-202404?wid=728&hei=666&fmt=png-alpha&.v=1713308651643',
      amazonLink: 'https://www.apple.com/th/shop/buy-ipad',
      description: 'iPad Pro รุ่น 11 นิ้ว (128 GB) ',
      price: '39900',
    },
    {
      id: 2,
      category: 'Apple watch',
      title: "Apple Watch SE",
      imgSrc: 'https://www.apple.com/th/apple-watch-se/images/overview/hero/hero__f76n0zejlxqq_medium_2x.jpg',
      amazonLink: 'https://www.apple.com/th/apple-watch-se/',
      description: 'ตัวเรือนอะลูมิเนียมขนาด 44 มม. หรือ 40 มม.',
      price: '7900',
    },
    {
      id: 6,
      category: 'iphone',
      title: "iphone 15",
      imgSrc: 'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch_AV1?wid=5120&hei=2880&fmt=webp&qlt=70&.v=cHJOTXEwTU92OEtKVDV2cVB1R2FTSjlERndlRTljaUdZeHJGM3dlLzR2L2RJbmltQWhGZkQyVGNjT3IyemNOZWd2S3NaRzcrU0dmYjNHTUFiMnlsWFRocXAvNjVVaCtjTTZGTUNzOU8wNkc5RGRYNnhoUFdnYk5iSlJkSmMrbGk=&traceId=1',
      amazonLink: 'https://www.apple.com/th/shop/buy-iphone/iphone-15',
      description: 'Apple iPhone 15 (128 GB)',
      price: '26900',
    },
    {
      id: 3,
      category: 'ipad',
      title: "ipad Air รุ่น11นิ้ว",
      imgSrc: 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/ipadair11-digitalmat-gallery-1-202404?wid=728&hei=666&fmt=jpeg&qlt=90&.v=1713308648429',
      amazonLink: 'https://www.apple.com/th/shop/buy-ipad',
      description: 'ipad Air รุ่น 11 นิ้ว (128GB)',
      price: '23900',
    },
    {
      id: 4,
      category: 'Mac',
      title: "MacBook Pro รุ่น 14 M3",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://www.apple.com/th/macbook-pro/',
      description: 'MacBook Pro รุ่น 14 M3 (128 GB)',
      price: '59900',
    },
    {
      id: 9,
      category: 'Mac',
      title: "i Mac",
      imgSrc: 'https://www.apple.com/v/imac/p/images/overview/color_front_green__eb8qbnemmre6_medium_2x.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'ชิป Apple M3 หน่วยความจำแบบรวมขนาด 8GB ถึง 24GB',
      price: '49900',
    },
    {
      id: 11,
      category: 'iphone',
      title: "iphone 16",
      imgSrc: 'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch_AV1?wid=5120&hei=2880&fmt=webp&qlt=70&.v=UXp1U3VDY3IyR1hNdHZwdFdOLzg1V0tFK1lhSCtYSGRqMUdhR284NTN4L2RJbmltQWhGZkQyVGNjT3IyemNOZWd2S3NaRzcrU0dmYjNHTUFiMnlsWFRocXAvNjVVaCtjTTZGTUNzOU8wNkVpZ3JSOHVOUHZSUHBkZzU2ZUh5WUo=&traceId=1',
      amazonLink: 'https://www.apple.com/th/shop/buy-iphone/iphone-16',
      description: 'Apple iPhone 16 (128 GB) ',
      price: '29990',
    },
    {
      id: 10,
      category: 'Mac',
      title: "MacBook Air 13 M1",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air  M1 chip, (128 GB)',
      price: '35000',
    },
    {
      id: 12,
      category: 'iphone',
      title: "iphon SE",
      imgSrc: 'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-se-finish-select-202207-midnight?wid=5120&hei=2880&fmt=webp&qlt=70&.v=VEhreGxMWU8vckorVEJ3dVU2RjJZWEE5c2FxTFBHYVd1Uk1sVVFiM0hqMXJnV2xBenVhdk9GcDNOWlRHZmVzbkFLaEM4VGVnOFFZVWtXR1EwaEFhTXlMTDB4bzVKMFI3VTBnTXkraEVFbWpVRnc4ellBTGJYT3ArblVqa3p3OEw=&traceId=1',
      amazonLink: 'https://www.apple.com/th/shop/buy-iphone/iphone-se',
      description: 'Apple iphon SE',
      price: '89999',
    },
    {
      id: 12,
      category: 'Apple watch',
      title: "Apple watch Series10",
      imgSrc: 'https://www.apple.com/v/apple-watch-series-10/a/images/overview/contrast/product_s10__d7ch2jhtbhme_medium_2x.png',
      amazonLink: 'https://www.apple.com/th/apple-watch-series-10/',
      description: 'ตัวเรือนอะลูมิเนียมหรือไทเทเนียม46 มม. หรือ 42 มม.',
      price: '14900',
    },
    

  ]