export const items =  [
    {
      id: 1,
      category: 'iphone',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/618Bb+QzCmL._AC_SR230,210_QL70_.jpg',
      amazonLink: 'https://www.apple.com/th/shop/buy-iphone/iphone-14',
      description: 'Apple iPhone 14 (128 GB)',
      price: '22900',
    },
    {
      id: 5,
      category: 'Mac',
      title: "MacBook Air รุ่น 13 M2",
      imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._AC_UY436_QL65_.jpg',
      amazonLink: 'https://www.apple.com/th/macbook-air/',
      description: 'ขนาด 13.6 นิ้ว หรือ 15.3 นิ้ว2 256GB ถึง 2TB',
      price: '43900',
    },
    {
      id: 7,
      category: 'ipad',
      title: "iPad Pro รุ่น 11 นิ้ว",
      imgSrc: 'https://m.media-amazon.com/images/I/4182G5WAIIL._AC_UF480,480_SR480,480_.jpg',
      amazonLink: 'https://www.apple.com/th/shop/buy-ipad',
      description: 'iPad Pro รุ่น 11 นิ้ว (128 GB) ',
      price: '39900',
    },
    {
      id: 2,
      category: 'Apple watch',
      title: "Apple Watch SE",
      imgSrc: 'https://m.media-amazon.com/images/I/61sJ+aPzOyL._AC_UL640_QL65_.jpg',
      amazonLink: 'https://www.apple.com/th/apple-watch-se/',
      description: 'ตัวเรือนอะลูมิเนียมขนาด 44 มม. หรือ 40 มม.',
      price: '7900',
    },
    {
      id: 6,
      category: 'iphone',
      title: "iphone 15",
      imgSrc: 'https://m.media-amazon.com/images/I/61cwywLZR-L._AC_SR292,236_QL70_.jpg',
      amazonLink: 'https://www.apple.com/th/shop/buy-iphone/iphone-15',
      description: 'Apple iPhone 15 (128 GB)',
      price: '26900',
    },
    {
      id: 3,
      category: 'ipad',
      title: "ipad Air รุ่น11นิ้ว",
      imgSrc: 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/ipadair11-digitalmat-gallery-1-202404?wid=728&hei=666&fmt=jpeg&qlt=90&.v=1713308648429',
      amazonLink: 'https://www.apple.com/th/shop/buy-ipad',
      description: 'ipad Air รุ่น 11 นิ้ว (128GB)',
      price: '23900',
    },
    {
      id: 4,
      category: 'Mac',
      title: "MacBook Pro รุ่น 14 M3",
      imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._AC_UY436_QL65_.jpg',
      amazonLink: 'https://www.apple.com/th/macbook-pro/',
      description: 'MacBook Pro รุ่น 14 M3 (128 GB)',
      price: '59900',
    },
    {
      id: 9,
      category: 'Mac',
      title: "i Mac",
      imgSrc: 'https://www.apple.com/v/imac/p/images/overview/color_front_green__eb8qbnemmre6_medium_2x.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'ชิป Apple M3 หน่วยความจำแบบรวมขนาด 8GB ถึง 24GB',
      price: '49900',
    },
    {
      id: 11,
      category: 'iphone',
      title: "iphone 16",
      imgSrc: 'https://images-eu.ssl-images-amazon.com/images/I/61DjMd76QnL._AC_UL330_SR330,330_.jpg',
      amazonLink: 'https://www.apple.com/th/shop/buy-iphone/iphone-16',
      description: 'Apple iPhone 16 (128 GB) ',
      price: '29990',
    },
    {
      id: 10,
      category: 'Mac',
      title: "MacBook Air 13 M1",
      imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._AC_UY436_QL65_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air  M1 chip, (128 GB)',
      price: '35000',
    },
    {
      id: 12,
      category: 'iphone',
      title: "iphon 13",
      imgSrc: 'https://images-eu.ssl-images-amazon.com/images/I/71GLMJ7TQiL._AC_UL330_SR330,330_.jpg',
      amazonLink: 'https://www.apple.com/th/shop/buy-iphone/iphone-se',
      description: 'Apple iphon13(128GB)',
      price: '29000',
    },
    {
      id: 12,
      category: 'Apple watch',
      title: "Apple watch Series10",
      imgSrc: 'https://m.media-amazon.com/images/I/61I431q8rhL._AC_UL640_QL65_.jpg',
      amazonLink: 'https://www.apple.com/th/apple-watch-series-10/',
      description: 'ตัวเรือนอะลูมิเนียมหรือไทเทเนียม46 มม. หรือ 42 มม.',
      price: '14900',
    },
    

  ]